name: Deploy Monitoring
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Grafana
    runs-on: self-hosted
    env:
      GRAFANA_HOST: "192.168.2.121"
      DOCKER_CONTEXT_NAME: grafana-ctx
      DOCKER_PROJECT_NAME: grafana
      DOCKER_COMPOSE_FILE: monitoring.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run command on remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.GRAFANA_HOST }}
          # todo: add these secrets to your Github Secrets
          username: ${{ secrets.GRAFANA_SSH_USERNAME }}
          password: ${{ secrets.GRAFANA_SSH_PASSWORD }}
          script: |
            cd /data/proxmox-docker-iac
            git pull origin master

      - name: Set up Docker context
        run: |
          docker context \
            create ${{ env.DOCKER_CONTEXT_NAME }} \
            --docker host="tcp://${{ env.GRAFANA_HOST }}:2375"

      - name: Deploy with Docker Compose
        run: |
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            --project-name ${{ env.DOCKER_PROJECT_NAME }} up -d --remove-orphans --force-recreate

      - name: Cleanup Docker context
        if: always()
        run: |
          docker context rm ${{ env.DOCKER_CONTEXT_NAME }} --force
